package icpmapp.entities;

public enum SessionType {
    KEYNOTE,
    FOOD,
    COFFEE,
    PRACTICAL,
    QnA,
    PANEL,
    ai4bpm, 
    automate,
    vipra,
    bpmeetiot,
    prody,
    objects,
    plc,
    innov8bpm,
    nlp4bpm,
    dlt4bpm,
    fmbpm,
    MAIN,
    BPMFORUM,
    PROCESSTECHNOLOGYFORUM,
    RESPONSIBLEBPMFORUM,
    INDUSTRYFORUM,
    EDUCATORSFORUM,
    DOCTORALCONSORTIUM,
    TUTORIAL,
    JOURNALFIRST,
    DEMO    
}
